# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

lang: en-US
title: Gruvw
email: gruvw.dev@gmail.com
description: "Coding projects website"
baseurl: "" # the optional subpath of your site, e.g. "/blog"
url: "https://gruvw.com" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
author:
  name: Lucas Jung
  # twitter:
  picture: assets/images/author/lucas_jung-min.jpg
# twitter_username:
github_username: gruvw
linkedin_username: jung-lucas
logo: "/assets/images/main/gruvw_logo.png" # path of site logo, e.g. "/assets/images/logo.png"
search: true # true, false (default)
search_full_content: false # true, false (default)
# TODO setup angolia search
# search_provider: algolia # lunr (default), algolia
# algolia:
#   application_id: # YOUR_APPLICATION_ID
#   index_name: # YOUR_INDEX_NAME
#   search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
#   powered_by: # true (default), false

# Build settings
markdown: kramdown
# theme: jekyll-theme-basically-basic
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-toc
  - jemoji
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 2
paginate_path: /page:num/

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs # ignore Basically Basic sample site
  - /example # ignore Basically Basic dev site

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true

toc:
  min_level: 1
  max_level: 3

google_analytics: UA-174941171-1
