name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  json-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Build resume
      - uses: kelvintaywl/action-jsonresume-export@v1
        name: Export resume as HTML
        with:
          theme: flat
          resume_filepath: resume.json
          output_filepath: json_resume.html

      - name: Commit published HTML
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain json_resume.html)" ]; then
            git add json_resume.html
            git commit -m "[ci skip] update resume page"
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}

      - name: Retrieve push
        run: |
          echo "commit_hash=$(git rev-parse HEAD)"
          echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  github-pages:
    needs: json-resume
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.json-resume.outputs.commit_hash }}
          # ref: ${{ github.ref }}

      # Use GitHub Actions' cache to cache dependencies on servers
      - name: Get cached gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build and deploy
        uses: helaili/jekyll-action@v2
        with:
          pre_build_commands: git config --global http.version HTTP/1.1; apk fetch git-lfs;
          token: ${{ secrets.GH_TOKEN }}
          target_branch: gh-pages
