name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  json-resume:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Export resume.json as HTML
        uses: kelvintaywl/action-jsonresume-export@v1
        with:
          theme: flat
          resume_filepath: resume.json
          output_filepath: json_resume.html

      # Open links in iframe to new tab
      - name: Add base tag
        run: "sed -i '4i<base target=\"_blank\">' json_resume.html"

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[ci skip] Built json_resume.html"
          file_pattern: json_resume.html

  github-pages:
    needs: json-resume
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # Use GitHub Actions' cache to cache dependencies on servers
      - name: Get cached gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build and deploy
        uses: helaili/jekyll-action@v2
        with:
          pre_build_commands: git config --global http.version HTTP/1.1; apk fetch git-lfs;
          token: ${{ secrets.GH_TOKEN }}
          target_branch: gh-pages
